package com.example.goinjava;

import android.annotation.SuppressLint;
import android.os.Bundle;
import android.util.Log;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;

// The Go library generated by gomobile
import golang.Golang;

public class MainActivity extends AppCompatActivity {

    @SuppressLint("SetTextI18n")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        EditText nameInput = findViewById(R.id.name);
        EditText input1 = findViewById(R.id.num1);
        EditText input2 = findViewById(R.id.num2);
        Button calcButton = findViewById(R.id.btn_calculate);
        TextView resultView = findViewById(R.id.sample_text);

        calcButton.setOnClickListener(v -> {
            try {
                String name = nameInput.getText().toString();
                double firstValue = Double.parseDouble(input1.getText().toString());
                double secondValue = Double.parseDouble(input2.getText().toString());

                String greeting = Golang.hello(name);
                double sum = Golang.add(firstValue, secondValue);
                double diff = firstValue > secondValue ? Golang.subtract(firstValue, secondValue): Golang.subtract(secondValue, firstValue);
                double mul = Golang.multiply(firstValue, secondValue);
                double ratio = firstValue > secondValue ? Golang.divide(firstValue, secondValue): Golang.divide(secondValue, firstValue);

                String sb = greeting + "\n\n" +
                        "Sum: " + sum + "\n" +
                        "Difference: " + diff + "\n" +
                        "Product: " + mul + "\n" +
                        "Ratio: " + ratio;

                resultView.setText(sb);

            } catch (NumberFormatException e) {
                resultView.setText("Please enter valid numbers");
            } catch (Exception e) {
                Log.e("GoMobile", "Error calling Go code", e);
                resultView.setText("Go calculation error: " + e.getMessage());
            }
        });
    }
}